-- Seed data harvested from the source database project by Modernizer — regenerated each run.
-- These rows are the application's own configuration, not sample data: without them a
-- data-driven application has nothing to render.
-- Every insert is guarded on the row's key. Nothing is deleted and nothing is overwritten,
-- so this is safe to re-run and can never destroy a row someone added.

-- DataView: 4 row(s)
INSERT INTO [DataView] ([ViewID], [Title], [DataSource], [MainTable], [Primarykey], [ModificationProcedure], [ViewProcedure], [DeleteProcedure], [ViewDescription], [OrderBy], [Flags], [DataTableModifierButtonStyle], [DataTableFlags], [DataTableDefaultPageSize], [DataTablePagingStyle], [Published], [RowReorderColumn], [IsSystemObject], [CSSTable]) SELECT -4, 'Navigation', 'CrudeDefault', 'portal.Navigation', 'NavId', '', '', '', '<p>Add, update, or remove the portal''s navigation links.</p>', '', 63, 1, 701, 50, 'full_numbers', 1, 'NavOrder', 1, 'table table-hover table-bordered table-striped' WHERE NOT EXISTS (SELECT 1 FROM [DataView] WHERE [ViewID] = -4);
INSERT INTO [DataView] ([ViewID], [Title], [DataSource], [MainTable], [Primarykey], [ModificationProcedure], [ViewProcedure], [DeleteProcedure], [ViewDescription], [OrderBy], [Flags], [DataTableModifierButtonStyle], [DataTableFlags], [DataTableDefaultPageSize], [DataTablePagingStyle], [Published], [RowReorderColumn], [IsSystemObject], [CSSTable]) SELECT -3, 'Data View Actions', 'CrudeDefault', 'portal.DataViewAction', 'ActionID', '', '', '', '', '', 191, 1, 1213, 50, 'first_last_numbers', 1, 'ActionOrder', 1, 'table table-hover table-bordered table-striped' WHERE NOT EXISTS (SELECT 1 FROM [DataView] WHERE [ViewID] = -3);
INSERT INTO [DataView] ([ViewID], [Title], [DataSource], [MainTable], [Primarykey], [ModificationProcedure], [ViewProcedure], [DeleteProcedure], [ViewDescription], [OrderBy], [Flags], [DataTableModifierButtonStyle], [DataTableFlags], [DataTableDefaultPageSize], [DataTablePagingStyle], [Published], [RowReorderColumn], [IsSystemObject], [CSSTable]) SELECT -2, 'Data View Fields', 'CrudeDefault', 'portal.DataViewField', 'FieldID', '', '', '', '', '', 191, 1, 9661, 50, 'first_last_numbers', 1, 'FieldOrder', 1, 'table table-hover table-bordered table-striped' WHERE NOT EXISTS (SELECT 1 FROM [DataView] WHERE [ViewID] = -2);
INSERT INTO [DataView] ([ViewID], [Title], [DataSource], [MainTable], [Primarykey], [ModificationProcedure], [ViewProcedure], [DeleteProcedure], [ViewDescription], [OrderBy], [Flags], [DataTableModifierButtonStyle], [DataTableFlags], [DataTableDefaultPageSize], [DataTablePagingStyle], [Published], [RowReorderColumn], [IsSystemObject], [CSSTable]) SELECT -1, 'Manage Data Views', 'CrudeDefault', 'portal.DataView', 'ViewID', '', '', '', '', '', 191, 5, 21, 50, 'first_last_numbers', 1, NULL, 1, 'table table-hover table-bordered table-striped' WHERE NOT EXISTS (SELECT 1 FROM [DataView] WHERE [ViewID] = -1);

-- DataViewField: 62 row(s)
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 1, 'Label', 'NavLabel', '1', 27, 4, '', 600, '', 1, '', '', '', '', '', '', '', 0, 0, 'The textual label displayed to users', NULL, NULL, 'Field_1' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 1);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 2, 'Parent Item', 'NavParentId', '5', 25, 1, '', 4, '', 1, 'portal.Navigation', 'NavId', 'NavLabel', '', '', '', '', 0, 0, 'The parent navigation link', NULL, NULL, 'Field_2' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 2);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 3, 'Sort Order', 'NavOrder', '3', 11, 2, '', 4, '', 1, '', '', '', '', NULL, NULL, '', NULL, NULL, 'Specifies the order in which the link will be displayed', NULL, NULL, 'Field_3' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 3);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 4, 'Link URI', 'NavUri', '1', 1, 6, '', 2000, '', 1, '', '', '', '', NULL, NULL, '', NULL, NULL, 'Link Path (can use AngularJS placeholders)', NULL, NULL, 'Field_4' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 4);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 5, 'Glyph Icon', 'NavGlyph', '1', 1, 3, '', 200, '', 1, '', '', '', '', NULL, NULL, '', NULL, NULL, 'Class string for Fontawesome icons', NULL, NULL, 'Field_5' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 5);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 6, 'Tooltip', 'NavTooltip', '1', 1, 5, '', 600, '', 1, '', '', '', '', NULL, NULL, '', NULL, NULL, 'The tooltip that would be displayed upon mouse-over', NULL, NULL, 'Field_6' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 6);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 7, 'Data View', 'ViewID', '5', 17, 8, '', 4, '', 1, 'portal.DataView', 'ViewId', 'Title', '', '', '', '', 0, 0, 'Link to a specific DataView (link will be active when that dataview is opened)', NULL, NULL, 'Field_7' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 7);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -4, 8, 'Open URI in IFRAME', 'OpenUriInIFRAME', '9', 9, 7, 'false', 5, '', 1, '', '', '', '', '', '', '', 0, 0, '', NULL, NULL, 'Field_8' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 8);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 9, 'Data View', 'ViewID', '5', 27, 1, '', 4, '', 1, '[portal].[DataView]', 'ViewID', 'Title', '', '', '', '', NULL, NULL, '', '', '', 'dataview' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 9);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 10, 'Action Label', 'ActionLabel', '1', 27, 6, '', 100, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Field_111' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 10);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 11, 'Parent Action', 'ParentActionID', '5', 25, 3, '', 4, '', 1, 'portal.DataViewAction', 'ActionID', 'ActionLabel', 'DataViewTitle', '', '', '', 0, 0, '', NULL, NULL, 'Field_112' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 11);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 12, 'Action Tooltip', 'ActionTooltip', '2', 17, 10, '', 300, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Field_113' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 12);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 13, 'Action Description', 'ActionDescription', '2', 17, 11, '', 1000, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, 'Field_114' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 13);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 14, 'Action Order', 'ActionOrder', '3', 11, 4, '', 4, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Field_115' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 14);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 15, 'Require Confirmation', 'RequireConfirmation', '9', 1, 8, '', 1, '', 1, '', '', '', '', NULL, NULL, '', 0, 0, '', NULL, NULL, 'Field_116' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 15);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 16, 'Open URL In New Window', 'OpenURLInNewWindow', '9', 1, 9, '', 1, '', 1, '', '', '', '', NULL, NULL, '', 0, 0, '', NULL, NULL, 'Field_117' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 16);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 17, 'Action Expression', 'ActionExpression', '2', 17, 7, '', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, 'Field_118' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 17);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 18, 'Glyph Icon', 'GlyphIcon', '1', 1, 12, '', 50, '', 1, '', '', '', '', NULL, NULL, '', 0, 0, '', NULL, NULL, 'Field_119' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 18);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 19, 'Is Per Row', 'IsPerRow', '9', 25, 2, '', 1, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Field_120' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 19);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 20, 'CSS Button', 'CSSButton', '1', 1, 13, 'btn btn-primary btn-sm', 50, '', 1, '', '', '', '', '', '', '', 0, 0, '', '', '', 'Field_121' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 20);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 21, 'Action Type', 'ActionType', '5', 27, 5, 'url', 20, '', 1, 'portal.DataViewActionTypes', 'TypeValue', 'TypeLabel', '', '', '', '', 0, 0, 'Choose the type of action behavior', NULL, NULL, 'Field_122' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 21);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -3, 22, 'Data View Title', 'DataViewTitle', '1', 5, 14, '', 100, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', '', 'Field_123' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 22);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 23, 'Data View', 'ViewID', '5', 19, 1, '', 4, 'dataview.asp?ViewId={{this}}', 1, '[portal].[DataView]', 'ViewID', 'Title', '', '', '', '', 0, 0, '', '', '', 'dataview' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 23);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 24, 'Label', 'FieldLabel', '1', 27, 3, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, 'The field label displayed to the user', '', '', 'Field_141' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 24);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 25, 'Field Source', 'FieldSource', '1', 9, 4, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, 'The actual column name from the database', NULL, NULL, 'Field_142' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 25);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 26, 'Field Type', 'FieldType', '5', 27, 6, '1', 50, '', 1, 'portal.DataViewFieldTypes', 'TypeValue', 'TypeLabel', 'TypeGroup', '', '', '', 0, 0, '', '', 'The data type for this field', 'Field_143' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 26);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 27, 'Properties', 'FieldFlags', '28', 9, 7, '1', 4, '', 1, 'portal.DataViewFieldFlags', 'FlagValue', 'FlagLabel', '', 'FlagGlyph', '', '', 0, 0, '', NULL, NULL, 'Field_144' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 27);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 28, 'Field Order', 'FieldOrder', '3', 11, 2, '1', 4, '', 1, '', '', '', '', '', '', '', 0, 0, '', '', 'The display order of this field', 'Field_145' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 28);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 29, 'Default Value', 'DefaultValue', '1', 1, 9, '', 1000, '', 1, '', '', '', '', '', '', '', 0, 0, 'The default value automatically filled out when adding a new item', NULL, NULL, 'Field_146' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 29);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 30, 'Max Length', 'MaxLength', '3', 1, 10, '', 4, '', 1, '', '', '', '', '', '', '', 0, 0, 'Relevant to textual field types such as Text, Password, Email, Phone, etc.', NULL, NULL, 'Field_147' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 30);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 31, 'Link URL', 'UriPath', '1', 1, 11, '', 1000, '', 1, '', '', '', '', '', '', '', 0, 0, 'Provide a URL expression to make the field clickable in the items list. You can use placeholders here.', NULL, NULL, 'Field_148' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 31);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 32, 'Link Style', 'UriStyle', '5', 1, 12, '1', 4, '', 1, 'portal.DataViewUriStyles', 'StyleValue', 'StyleLabel', '', 'StyleGlyph', '', '', 0, 0, 'Choose how the link would look like, if URL Path was specified', NULL, NULL, 'Field_149' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 32);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 33, 'Linked Table', 'LinkedTable', '1', 1, 13, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, 'Used for Lookup field types', NULL, NULL, 'Field_150' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 33);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 34, 'Linked Table Value Field', 'LinkedTableValueField', '1', 1, 14, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, 'Used for Lookup field types', NULL, NULL, 'Field_151' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 34);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 35, 'Linked Table Title Field', 'LinkedTableTitleField', '1', 1, 15, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, 'Used for Lookup field types', NULL, NULL, 'Field_152' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 35);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 36, 'Linked Table Group Field', 'LinkedTableGroupField', '1', 1, 16, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, 'Used for Lookup field types', NULL, NULL, 'Field_153' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 36);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 37, 'Linked Table Glyph Field', 'LinkedTableGlyphField', '1', 1, 17, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, '', NULL, NULL, 'Field_154' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 37);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 38, 'Linked Table Tooltip Field', 'LinkedTableTooltipField', '1', 1, 18, '', 300, '', 1, '', '', '', '', '', '', '', 0, 0, 'Used for Lookup field types', NULL, NULL, 'Field_155' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 38);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 39, 'Linked Table Addition', 'LinkedTableAddition', '2', 1, 19, '', 1000, '', 1, '', '', '', '', '', '', '', 0, 5, 'Used for Lookup field types. Unrestricted SQL expression added after the table name.', NULL, NULL, 'Field_156' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 39);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 40, 'Width', 'Width', '3', 1, 20, '', 4, '', 1, '', '', '', '', '', '', '', 0, 0, 'Horizontal width of the input field', NULL, NULL, 'Field_157' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 40);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 41, 'Height', 'Height', '3', 1, 21, '', 4, '', 1, '', '', '', '', '', '', '', 0, 0, 'Vertical height of the input (for Text Area and Multi-Selection box)', NULL, NULL, 'Field_158' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 41);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 42, 'Field Description', 'FieldDescription', '14', 1, 22, '', 4000, '', 1, '', '', '', '', '', '', '', 100, 30, 'A rich text formatted description to be used as the "help" text for the field', '', NULL, 'Field_159' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 42);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 43, 'Format Pattern', 'FormatPattern', '1', 1, 23, '', 100, '', 1, '', '', '', '', '', '', '', 0, 0, 'Used for enforcing a pattern in textual fields, using a regular expression', NULL, NULL, 'Field_160' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 43);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 44, 'Field Tooltip', 'FieldTooltip', '1', 1, 8, '', NULL, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', NULL, 'Field_161' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 44);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -2, 45, 'Field Identifier', 'FieldIdentifier', '1', 3, 5, '', 100, '', 1, '', '', '', '', '', '', '', 100, 0, 'Write here a unique identifying name for the field, which can later be used in placeholders, URL parameters, and custom actions', NULL, NULL, 'Field_890337931' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 45);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 46, 'Title', 'Title', '1', 27, 1, '', 100, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'The title will be displayed at the top of the page', 'title' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 46);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 47, 'Data Source', 'DataSource', '1', 19, 4, 'CrudeDefault', 200, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Choose the connection string to use (from web.config)', 'datasource' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 47);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 48, 'Main Table Name', 'MainTable', '1', 19, 5, '', 300, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'This is the main database table from which data will be queried and modified (unless you specified replacement stored procedures)', 'maintable' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 48);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 49, 'Primary Key', 'Primarykey', '1', 17, 6, '', 300, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Database column name which will serve as a primary key in the aforementioned table', 'primarykey' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 49);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 50, 'Modification Procedure', 'ModificationProcedure', '1', 1, 10, '', 300, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Execute this stored procedure instead of modifying the main table directly', 'modificationproc' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 50);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 51, 'Source Procedure', 'ViewProcedure', '1', 1, 9, '', 300, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Execute this stored procedure instead of querying directly from the main table', 'sourceproc' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 51);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 52, 'Delete Procedure', 'DeleteProcedure', '1', 1, 11, '', 300, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Execute this stored procedure instead of deleting from the main table directly', 'deleteproc' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 52);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 53, 'Description', 'ViewDescription', '14', 17, 3, '', 4000, '', 1, '', '', '', '', '', '', '', 100, 10, '', '', 'This rich text will be displayed below the dataview title, above the data table', 'description' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 53);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 54, 'Order By', 'OrderBy', '1', 1, 7, '', 300, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Default sorting expression when querying from the database table', 'orderby' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 54);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 55, 'Properties', 'Flags', '28', 9, 12, '63', 4, '', 1, 'portal.DataViewFlags', 'FlagValue', 'FlagLabel', '', 'FlagGlyph', 'FlagLabel', '', NULL, NULL, '', '', '', 'properties' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 55);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 56, 'Data Table Row Buttons Styles', 'DataTableModifierButtonStyle', '5', 3, 14, '1', 2, '', 1, 'portal.DataViewModifierButtonStyles', 'StyleValue', 'StyleLabel', '', '', 'StyleLabel', '', NULL, NULL, '', '', 'Choose how the edit/clone/delete buttons would look like', 'rowbuttonstyle' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 56);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 57, 'DataTable Options', 'DataTableFlags', '28', 9, 13, '65469', 4, '', 1, 'portal.DataViewDataTableFlags', 'FlagValue', 'FlagLabel', '', 'FlagGlyph', 'FlagTooltip', '', NULL, NULL, '', '', '', 'dt_options' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 57);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 58, 'Data Table Default Page Size', 'DataTableDefaultPageSize', '3', 3, 15, '25', 4, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Choose the default number of rows per page', 'dt_defaultpagesize' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 58);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 59, 'Data Table Paging Style', 'DataTablePagingStyle', '5', 3, 16, 'first_last_numbers', 20, '', 1, 'portal.DataViewPagingTypes', 'StyleValue', 'StyleLabel', '', '', 'StyleLabel', '', NULL, NULL, '', '', 'Choose how the pagination buttons would look like', 'dt_pagingtype' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 59);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 60, 'Published', 'Published', '9', 25, 2, '1', 1, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'Sets whether this dataview is visible to end-users', 'published' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 60);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 61, 'Row Reorder Column', 'RowReorderColumn', '1', 1, 8, '', 200, '', 1, '', '', '', '', '', '', '', NULL, NULL, '', '', 'If specified, this column will be used for sorting and re-ordering items in the data table', 'rowreordercol' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 61);
INSERT INTO [DataViewField] ([ViewID], [FieldID], [FieldLabel], [FieldSource], [FieldType], [FieldFlags], [FieldOrder], [DefaultValue], [MaxLength], [UriPath], [UriStyle], [LinkedTable], [LinkedTableValueField], [LinkedTableTitleField], [LinkedTableGroupField], [LinkedTableGlyphField], [LinkedTableTooltipField], [LinkedTableAddition], [Width], [Height], [FieldDescription], [FormatPattern], [FieldTooltip], [FieldIdentifier]) SELECT -1, 62, 'DataTable Style', 'CSSTable', '1', 3, 17, 'table table-hover table-bordered table-striped', 100, '', 1, '', '', '', '', '', '', '', 100, NULL, '', '', 'Choose the CSS class name', 'dt_style' WHERE NOT EXISTS (SELECT 1 FROM [DataViewField] WHERE [FieldID] = 62);

-- DataViewAction: 14 row(s)
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 1, -4, 'Custom Action', NULL, 'This is a custom inline action button', '', 1, 1, 1, 'alert("You''ve activated a custom inline button. Check the console.")
console.log(tr)
console.log(r);', 'fa fa-magic', 1, 'btn btn-info btn-sm', 'javascript' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 1);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 2, -4, 'Inspect Selected', NULL, '', '', 2, 0, 1, 'var r = dt.rows({ selected: true }).data()
alert("Inspecting " + r.length + " rows (check the console)")
console.log(r);', 'fas fa-info-circle', 0, 'btn btn-info btn-sm', 'javascript' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 2);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 3, -4, 'Custom Inline Action', NULL, 'This is a custom inline row action button', '', 2, 1, 1, 'alert("You''ve activated a custom inline button. Check the console.")
console.log(tr)
console.log(r);', 'fa fa-magic', 1, 'btn btn-info btn-sm', 'javascript' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 3);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 4, -4, 'Inspect Selected Rows', NULL, '', '', 1, 0, 1, 'var r = dt.rows({ selected: true }).data()
alert("Inspecting " + r.length + " rows (check the console)")
console.log(r);', 'fas fa-info-circle', 0, 'btn btn-info btn-sm', 'javascript' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 4);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 5, -3, 'Open Data View', NULL, 'View this dataview live', '', 2, 0, 0, 'dataview.asp?ViewID={{urlparam[dataview[search]]}}', 'fas fa-eye', 0, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 5);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 6, -3, 'Data View Fields', NULL, 'Manage this dataview''s fields', '', 3, 0, 0, 'dataview.asp?ViewID=-2&dataview[search]={{urlparam[dataview[search]]}}', 'fas fa-bars', 0, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 6);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 7, -3, 'Manage Data Views', NULL, 'Return to Data View Management', '', 1, 0, 0, 'dataview.asp?ViewID=-1', 'fas fa-cogs', 0, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 7);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 8, -2, 'Open Data View', NULL, 'View this dataview live', '', 2, 0, 0, 'dataview.asp?ViewID={{urlparam[dataview[search]]}}', 'fas fa-eye', 0, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 8);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 9, -2, 'Data View Actions', NULL, 'Manage Custom Actions for this DataView', '', 3, 0, 0, 'dataview.asp?ViewID=-3&dataview[search]={{urlparam[dataview[search]]}}', 'fas fa-bolt', 0, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 9);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 10, -2, 'Manage Data Views', NULL, 'Return to Data View Management', '', 1, 0, 0, 'dataview.asp?ViewID=-1', 'fas fa-cogs', 0, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 10);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 14, -2, 'Auto-Init Fields', NULL, 'Use underlying DB schema to automatically create any missing fields', '', 4, 1, 1, 'ajax_dataview.asp?ViewID={{urlparam[dataview[search]]}}&mode=autoinit', 'fas fa-database', 0, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 14);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 11, -1, 'Open', NULL, 'Open Data View', '', 1, 0, 0, 'dataview.asp?ViewID={{row[DT_RowId]}}', 'fas fa-eye', 1, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 11);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 12, -1, 'Fields', NULL, 'Data View Fields', '', 2, 0, 0, 'dataview.asp?ViewID=-2&dataview[search]={{row[DT_RowId]}}', 'fas fa-bars', 1, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 12);
INSERT INTO [DataViewAction] ([ActionID], [ViewID], [ActionLabel], [ParentActionID], [ActionTooltip], [ActionDescription], [ActionOrder], [RequireConfirmation], [OpenURLInNewWindow], [ActionExpression], [GlyphIcon], [IsPerRow], [CSSButton], [ActionType]) SELECT 13, -1, 'Actions', NULL, 'Data View Actions', '', 3, 0, 0, 'dataview.asp?ViewID=-3&dataview[search]={{row[DT_RowId]}}', 'fas fa-bolt', 1, 'btn btn-primary btn-sm', 'url' WHERE NOT EXISTS (SELECT 1 FROM [DataViewAction] WHERE [ActionID] = 13);

-- Navigation: 2 row(s)
INSERT INTO [Navigation] ([NavId], [NavLabel], [NavParentId], [NavOrder], [NavUri], [NavGlyph], [NavTooltip], [ViewID], [OpenUriInIFRAME]) SELECT 1, 'Manage Data Views', NULL, 1, '', 'fas fa-cogs', 'Click here to start creating content', -1, 0 WHERE NOT EXISTS (SELECT 1 FROM [Navigation] WHERE [NavId] = 1);
INSERT INTO [Navigation] ([NavId], [NavLabel], [NavParentId], [NavOrder], [NavUri], [NavGlyph], [NavTooltip], [ViewID], [OpenUriInIFRAME]) SELECT 2, 'Manage Navigation', NULL, 2, '', 'fas fa-link', 'Click to manage this navigation menu', -4, 0 WHERE NOT EXISTS (SELECT 1 FROM [Navigation] WHERE [NavId] = 2);

-- DataViewActionTypes: 4 row(s)
INSERT INTO [DataViewActionTypes] ([TypeValue], [TypeLabel], [TypeDefault]) SELECT 'javascript', 'DataTable Javascript Function', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewActionTypes] WHERE [TypeValue] = 'javascript');
INSERT INTO [DataViewActionTypes] ([TypeValue], [TypeLabel], [TypeDefault]) SELECT 'db_command', 'Database SQL Command', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewActionTypes] WHERE [TypeValue] = 'db_command');
INSERT INTO [DataViewActionTypes] ([TypeValue], [TypeLabel], [TypeDefault]) SELECT 'db_procedure', 'Database SQL Stored Procedure', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewActionTypes] WHERE [TypeValue] = 'db_procedure');
INSERT INTO [DataViewActionTypes] ([TypeValue], [TypeLabel], [TypeDefault]) SELECT 'url', 'HTTP Link', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewActionTypes] WHERE [TypeValue] = 'url');

-- DataViewChartTypes: 4 row(s)
INSERT INTO [DataViewChartTypes] ([TypeValue], [TypeLabel], [TypeCode]) SELECT 1, 'Line', 'line' WHERE NOT EXISTS (SELECT 1 FROM [DataViewChartTypes] WHERE [TypeValue] = 1);
INSERT INTO [DataViewChartTypes] ([TypeValue], [TypeLabel], [TypeCode]) SELECT 2, 'Area', 'area' WHERE NOT EXISTS (SELECT 1 FROM [DataViewChartTypes] WHERE [TypeValue] = 2);
INSERT INTO [DataViewChartTypes] ([TypeValue], [TypeLabel], [TypeCode]) SELECT 3, 'Donut', 'Donut' WHERE NOT EXISTS (SELECT 1 FROM [DataViewChartTypes] WHERE [TypeValue] = 3);
INSERT INTO [DataViewChartTypes] ([TypeValue], [TypeLabel], [TypeCode]) SELECT 4, 'Bar', 'Bar' WHERE NOT EXISTS (SELECT 1 FROM [DataViewChartTypes] WHERE [TypeValue] = 4);

-- DataViewDataTableFlags: 17 row(s)
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 1, 'Show Info', 'an info bar indicating how many rows out of what total are currently being showed', 'fas fa-info-circle', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 1);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 2, 'Column Footers', 'show column headers at the bottom of the table as well', 'fas fa-arrow-down', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 2);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 4, 'Enable Quick-Search', 'allow quick free-text search on the table', 'fas fa-search', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 4);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 8, 'Sortable Columns', 'columns can be dynamically sorted', 'fas fa-sort-amount-down', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 8);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 16, 'Pagination', 'split rows into pages based on page size', 'fas fa-ellipsis-h', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 16);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 32, 'Page Size Selection', 'allow users to select how many rows per page', 'fas fa-ellipsis-v', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 32);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 64, 'Client-Side State Save', 'save a cookie in the client browser with the quick-search and paging info, which would be restored upon next visit to page', 'far fa-save', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 64);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 128, 'Enable Advanced Search', 'allow advanced column-specific filters', 'fas fa-search', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 128);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 256, 'Enable Columns Visibility Toggle', 'allow toggling columns to be hidden or visible in the table', 'fas fa-eye-slash', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 256);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 512, 'Enable Row Details', 'allow expanding each table row to see the rest of the record details', 'fas fa-plus-circle', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 512);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 1024, 'Enable Row Selection', 'allows selection of multiple rows (for batch operations such as multiple delete)', 'fas fa-tasks', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 1024);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 2048, 'Export to Clipboard', 'allow copying table contents to clipboard', 'fas fa-paste', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 2048);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 4096, 'Export to CSV', 'allow exporting table contents to a CSV file', 'fas fa-file-alt', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 4096);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 8192, 'Export to Excel', 'allow exporting table contents to an Excel file', 'fas fa-file-excel', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 8192);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 16384, 'Export to PDF', 'allow exporting table contents to a PDF file', 'fas fa-file-pdf', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 16384);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 32768, 'Export to Print', 'allow printing the table contents', 'fas fa-print', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 32768);
INSERT INTO [DataViewDataTableFlags] ([FlagValue], [FlagLabel], [FlagTooltip], [FlagGlyph], [FlagDefault]) SELECT 65536, 'Fixed Table Headers', 'makes the table headers fixed in their place while scrolling', 'fas fa-thumbtack', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewDataTableFlags] WHERE [FlagValue] = 65536);

-- DataViewFieldFlags: 5 row(s)
INSERT INTO [DataViewFieldFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 1, 'Show in Form', 'fas fa-th-list', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldFlags] WHERE [FlagValue] = 1);
INSERT INTO [DataViewFieldFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 2, 'Required', 'fas fa-asterisk', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldFlags] WHERE [FlagValue] = 2);
INSERT INTO [DataViewFieldFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 4, 'Read Only', 'fas fa-eye', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldFlags] WHERE [FlagValue] = 4);
INSERT INTO [DataViewFieldFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 8, 'Show in Items List', 'fas fa-table', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldFlags] WHERE [FlagValue] = 8);
INSERT INTO [DataViewFieldFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 16, 'Show in Search', 'fas fa-search', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldFlags] WHERE [FlagValue] = 16);

-- DataViewFieldTypes: 29 row(s)
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 1, 'Text', '''', 'text', 'Text' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 1);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 2, 'Text Area', '''', 'textarea', 'Text' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 2);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 3, 'Integer', '', 'numeric', 'Numeric' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 3);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 4, 'Decimal', '', 'numeric', 'Numeric' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 4);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 5, 'Selection Dropdown Box', '', 'select', 'Single-Value Lookup' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 5);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 6, 'Multi-Selection Dropdown Box', '''', 'csv', 'Multi-Value Lookup' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 6);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 7, 'Date', '''', 'date', 'Date and Time' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 7);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 8, 'Date and Time', '''', 'datetime', 'Date and Time' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 8);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 9, 'Boolean Switch', '', 'boolean_switch', 'Boolean' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 9);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 10, 'Link', '''', 'link', 'External Resource' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 10);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 11, 'Image Source', '''', 'image', 'External Resource' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 11);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 12, 'Password', '''', 'password', 'Text' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 12);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 13, 'Time', '''', 'time', 'Date and Time' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 13);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 14, 'Rich Text', '''', 'rte', 'Text' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 14);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 15, 'E-Mail', '''', 'email', 'Text' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 15);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 16, 'Phone', '''', 'phone', 'Text' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 16);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 17, 'Multi-Selection Checkboxes', '''', 'csv_checkboxes', 'Multi-Value Lookup' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 17);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 18, 'Multi-Selection Switches', '''', 'csv_switches', 'Multi-Value Lookup' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 18);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 19, 'Multi-Selection Buttons', '''', 'csv_buttons', 'Multi-Value Lookup' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 19);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 20, 'Selection Buttons', '', 'select_buttons', 'Single-Value Lookup' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 20);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 21, 'Selection Switches', '', 'select_switches', 'Single-Value Lookup' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 21);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 22, 'Boolean Checkbox', '', 'boolean_checkbox', 'Boolean' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 22);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 23, 'Boolean Radios', '', 'boolean_radios', 'Boolean' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 23);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 24, 'Computed Expression', '''', 'formula', 'Miscellaneous' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 24);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 25, 'Document Download', '''', 'document', 'External Resource' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 25);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 26, 'Boolean Button', '', 'boolean_button', 'Boolean' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 26);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 27, 'Bitwise Checkboxes', '', 'bitwise_checkboxes', 'Bitwise' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 27);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 28, 'Bitwise Switches', '', 'bitwise_switches', 'Bitwise' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 28);
INSERT INTO [DataViewFieldTypes] ([TypeValue], [TypeLabel], [TypeWrappers], [TypeIdentifier], [TypeGroup]) SELECT 29, 'Bitwise Buttons', '', 'bitwise_buttons', 'Bitwise' WHERE NOT EXISTS (SELECT 1 FROM [DataViewFieldTypes] WHERE [TypeValue] = 29);

-- DataViewFlags: 9 row(s)
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 1, 'Allow Edit', 'fas fa-edit', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 1);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 2, 'Allow Add', 'fas fa-plus', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 2);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 4, 'Allow Delete', 'fas fa-trash-alt', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 4);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 8, 'Allow Clone', 'fas fa-clone', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 8);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 16, 'Enable Form', 'fas fa-th-list', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 16);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 32, 'Enable Items List', 'fas fa-table', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 32);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 64, 'Enable Charts', 'fas fa-chart-pie', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 64);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 128, 'Enable Custom Actions', 'fas fa-bolt', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 128);
INSERT INTO [DataViewFlags] ([FlagValue], [FlagLabel], [FlagGlyph], [FlagDefault]) SELECT 256, 'Enable Browse Module', 'far fa-window-maximize', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewFlags] WHERE [FlagValue] = 256);

-- DataViewModifierButtonStyles: 6 row(s)
INSERT INTO [DataViewModifierButtonStyles] ([StyleValue], [StyleLabel], [StyleClass], [ShowText], [ShowGlyph], [StyleDefault]) SELECT 1, 'Buttons - Icon and Text', 'btn btn-primary btn-sm', 1, 1, 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewModifierButtonStyles] WHERE [StyleValue] = 1);
INSERT INTO [DataViewModifierButtonStyles] ([StyleValue], [StyleLabel], [StyleClass], [ShowText], [ShowGlyph], [StyleDefault]) SELECT 2, 'Buttons - Icon Only', 'btn btn-primary btn-sm', 0, 1, 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewModifierButtonStyles] WHERE [StyleValue] = 2);
INSERT INTO [DataViewModifierButtonStyles] ([StyleValue], [StyleLabel], [StyleClass], [ShowText], [ShowGlyph], [StyleDefault]) SELECT 3, 'Buttons - Text Only', 'btn btn-primary btn-sm', 1, 0, 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewModifierButtonStyles] WHERE [StyleValue] = 3);
INSERT INTO [DataViewModifierButtonStyles] ([StyleValue], [StyleLabel], [StyleClass], [ShowText], [ShowGlyph], [StyleDefault]) SELECT 4, 'Hyperlink - Icon and Text', NULL, 1, 1, 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewModifierButtonStyles] WHERE [StyleValue] = 4);
INSERT INTO [DataViewModifierButtonStyles] ([StyleValue], [StyleLabel], [StyleClass], [ShowText], [ShowGlyph], [StyleDefault]) SELECT 5, 'Hyperlink - Icon Only', NULL, 0, 1, 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewModifierButtonStyles] WHERE [StyleValue] = 5);
INSERT INTO [DataViewModifierButtonStyles] ([StyleValue], [StyleLabel], [StyleClass], [ShowText], [ShowGlyph], [StyleDefault]) SELECT 6, 'Hyperlink - Text Only', NULL, 1, 0, 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewModifierButtonStyles] WHERE [StyleValue] = 6);

-- DataViewPagingTypes: 6 row(s)
INSERT INTO [DataViewPagingTypes] ([StyleValue], [StyleLabel], [StyleDefault]) SELECT 'full_numbers', 'First, Previous, Next and Last buttons, plus page numbers', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewPagingTypes] WHERE [StyleValue] = 'full_numbers');
INSERT INTO [DataViewPagingTypes] ([StyleValue], [StyleLabel], [StyleDefault]) SELECT 'simple_numbers', 'Previous and Next buttons, plus page numbers', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewPagingTypes] WHERE [StyleValue] = 'simple_numbers');
INSERT INTO [DataViewPagingTypes] ([StyleValue], [StyleLabel], [StyleDefault]) SELECT 'simple', 'Previous and Next buttons only', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewPagingTypes] WHERE [StyleValue] = 'simple');
INSERT INTO [DataViewPagingTypes] ([StyleValue], [StyleLabel], [StyleDefault]) SELECT 'numbers', 'Page number buttons only', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewPagingTypes] WHERE [StyleValue] = 'numbers');
INSERT INTO [DataViewPagingTypes] ([StyleValue], [StyleLabel], [StyleDefault]) SELECT 'full', 'First, Previous, Next and Last buttons', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewPagingTypes] WHERE [StyleValue] = 'full');
INSERT INTO [DataViewPagingTypes] ([StyleValue], [StyleLabel], [StyleDefault]) SELECT 'first_last_numbers', 'First and Last buttons, plus page numbers', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewPagingTypes] WHERE [StyleValue] = 'first_last_numbers');

-- DataViewUriStyles: 7 row(s)
INSERT INTO [DataViewUriStyles] ([StyleValue], [StyleLabel], [StyleClass], [StyleGlyph], [StyleDefault]) SELECT 1, 'Hyperlink', '', 'fa fa-link', 1 WHERE NOT EXISTS (SELECT 1 FROM [DataViewUriStyles] WHERE [StyleValue] = 1);
INSERT INTO [DataViewUriStyles] ([StyleValue], [StyleLabel], [StyleClass], [StyleGlyph], [StyleDefault]) SELECT 2, 'Button Default', 'btn btn-default btn-sm', 'fa fa-square', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewUriStyles] WHERE [StyleValue] = 2);
INSERT INTO [DataViewUriStyles] ([StyleValue], [StyleLabel], [StyleClass], [StyleGlyph], [StyleDefault]) SELECT 3, 'Button Primary', 'btn btn-primary btn-sm', 'fa fa-square', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewUriStyles] WHERE [StyleValue] = 3);
INSERT INTO [DataViewUriStyles] ([StyleValue], [StyleLabel], [StyleClass], [StyleGlyph], [StyleDefault]) SELECT 4, 'Button Success', 'btn btn-success btn-sm', 'fa fa-square', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewUriStyles] WHERE [StyleValue] = 4);
INSERT INTO [DataViewUriStyles] ([StyleValue], [StyleLabel], [StyleClass], [StyleGlyph], [StyleDefault]) SELECT 5, 'Button Info', 'btn btn-info btn-sm', 'fa fa-square', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewUriStyles] WHERE [StyleValue] = 5);
INSERT INTO [DataViewUriStyles] ([StyleValue], [StyleLabel], [StyleClass], [StyleGlyph], [StyleDefault]) SELECT 6, 'Button Warning', 'btn btn-warning btn-sm', 'fa fa-square', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewUriStyles] WHERE [StyleValue] = 6);
INSERT INTO [DataViewUriStyles] ([StyleValue], [StyleLabel], [StyleClass], [StyleGlyph], [StyleDefault]) SELECT 7, 'Button Danger', 'btn btn-danger btn-sm', 'fa fa-square', 0 WHERE NOT EXISTS (SELECT 1 FROM [DataViewUriStyles] WHERE [StyleValue] = 7);
